/**
 * Data Source Configuration
 * This file is auto-generated by GitHub Actions during deployment
 * DO NOT EDIT MANUALLY
 *
 * The repository information is injected during the CI/CD build process
 * to enable fetching data from the data branch
 */

const INJECTED_REPO_OWNER = 'PLACEHOLDER_REPO_OWNER';
const INJECTED_REPO_NAME = 'PLACEHOLDER_REPO_NAME';

function getInjectedValue(value, fallback) {
    return value && !value.startsWith('PLACEHOLDER_') ? value : fallback;
}

function detectGitHubPagesRepository() {
    if (typeof window === 'undefined' || !window.location) {
        return {};
    }

    const hostname = window.location.hostname;
    if (!hostname.endsWith('.github.io')) {
        return {};
    }

    const repoOwner = hostname.replace(/\.github\.io$/, '');
    const pathParts = window.location.pathname.split('/').filter(Boolean);
    const repoName = pathParts[0] || `${repoOwner}.github.io`;

    return { repoOwner, repoName };
}

const detectedRepository = detectGitHubPagesRepository();
const DATA_CACHE_VERSION = Date.now();

const DATA_CONFIG = {
    /**
     * GitHub repository owner (username)
     * This will be replaced during GitHub Actions workflow execution
     */
    repoOwner: detectedRepository.repoOwner || getInjectedValue(INJECTED_REPO_OWNER, 'dw-dengwei'),

    /**
     * GitHub repository name
     * This will be replaced during GitHub Actions workflow execution
     */
    repoName: detectedRepository.repoName || getInjectedValue(INJECTED_REPO_NAME, 'daily-arXiv-ai-enhanced'),

    /**
     * Data branch name
     * Default: 'data'
     */
    dataBranch: 'data',

    /**
     * Get the base URL for raw GitHub content from data branch
     * @returns {string} Base URL for raw GitHub content
     */
    getDataBaseUrl: function() {
        return `https://raw.githubusercontent.com/${this.repoOwner}/${this.repoName}/${this.dataBranch}`;
    },

    /**
     * Get the full URL for a data file
     * @param {string} filePath - Relative path to the data file (e.g., 'data/2025-01-01.jsonl')
     * @returns {string} Full URL to the data file
     */
    getDataUrl: function(filePath) {
        return `${this.getDataBaseUrl()}/${filePath}?cache=${DATA_CACHE_VERSION}`;
    }
};

